### PR TITLE
Add dump/restore/readonly functionality

### PR DESCRIPTION
**Pull request by jbergknoff**
Notes:

* ElasticSearch doesn't seem to have built-in support for "dump to stdout/restore from stdin", so this image uses the [elasticdump](https://github.com/taskrabbit/elasticsearch-dump) tool to make that happen.
* ElasticSearch doesn't seem to have built-in support for a read-only mode. The accepted ways to enable read-only mode are (1) a plugin [readonlyrest](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin), and (2) proxying through nginx and only allowing `GET` requests. I went with the latter (I also tried the plugin but couldn't get it set up correctly).

### CODE REVIEW

**Comment by jbergknoff** [comment]
@fancyremarker @aaw

Also, should read-only mode also support `OPTIONS` requests? I see that CORS was enabled in the ES config file.

**Comment by aaw** [comment]
:+1:

Allowing `OPTIONS` in addition to `GET` in read-only mode sounds like a good idea.

**Comment by fancyremarker** [comment]
Clever implementation and agree about `OPTIONS`, and while not clearly necessary, `HEAD` can be included as the only other standard "safe" HTTP method.

**Comment by jbergknoff** [comment]
Good call @aaw @fancyremarker, I made the change so that read only mode allows `GET`, `HEAD` and `OPTIONS` requests.

**Comment by fancyremarker** [comment]
Thanks! Merging.

**Pull request merged**
