### PR TITLE
Elasticsearch 5 Support

### PR DESCRIPTION
**Pull request by krallin**
This adds autosizing of the ES Heap via the APTIBLE_CONTAINER_SIZE
environment variable if present (we use half of APTIBLE_CONTAINER_SIZE
for the ES Heap, which is what Elastic recommends), and adds support for
Elasticsearch 5.

Note that the underlying reason we needed to support
APTIBLE_CONTAINER_SIZE before supporting Elasticsearch 5 is that
Elasticsearch defaults to a heap that's too big for our default 1GB
container size.

Finally, note that this does not support --dump and --restore because
Elasticsearch 5 is not supported in elasticdump yet (which we use for
these). In practice, we don't allow cloning Elasticsearch databases, so
so these are never used anyway (plus, now that we have on-demand backup
and restore, cloning is increasingly irrelevant).

A few other notable changes:

- ES 5 uses Java 8.
- ES 5 uses a different repository.
- ES 5 no longer defaults to multicast discovery, so we no longer need
  to disable it.
- For backwards compatibility, if ES_HEAP_SIZE was present in the
  database's configuration (i.e. environment), we'll translate that into
  the relevant option for ES 5 (i.e. ES_JAVA_OPTS).

---

Note: I'm also fixing an unrelated nit in the wrapper script in a separate commit here.

cc @fancyremarker @blakepettersson

### CODE REVIEW

**Comment by krallin** [comment]
cc @fancyremarker @blakepettersson

**Comment by blakepettersson** [comment]
👍

**Comment by krallin** [comment]
Upon startup, Elasticsearch complains that it thinks our `vm.max_map_count` sysctl is too low:

```
[2016-11-25T12:47:37,783][WARN ][o.e.b.BootstrapCheck     ] [fdBJUoa] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```

Now, this doesn't prevent Elasticseach from starting, but the ES docs do indicate that [it's probably a good idea to increase it](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/setup-configuration.html#vm-max-map-count).

I don't think it's harmful to set this on DB instances (it certainly isn't nowhere near as potentially problematic as Redis' requirements to set `vm.overcommit_memory` to 1), I can make that change in our cookbook.

cc @fancyremarker

**Comment by zharben** [comment]
Yay! Thanks, @krallin and team

**Pull request merged**
